### ISSUE TITLE
Products/Search view - no search results

### ISSUE THREAD

**Issue by thurston-ssa** [EliZukowski16/FinalProject#4]
If I search for something and no results come back, i need some visual indication of that (like a transient message).

To reproduce:  go to products -> enter "schorr" in google search -> click search

Nothing happens; did something go wrong?  should i search again?  user has no idea, need to help them understand what happened; this likely will happen in a demo

@lslemp1 

**high priority**

**Comment by lslemp1** [comment]
@thurston-ssa verify

**Comment by thurston-ssa** [comment]
verified/closing
