### ISSUE TITLE
Admin:  Low Inventory - ordering inventory doesn't update inventory values

### ISSUE THREAD

**Issue by thurston-ssa** [EliZukowski16/FinalProject#5]
So if you go to low inventory and order more products and then click submit inventory; yes, it shows a success message, but if you go back to low inventory, the current inventory still remains at the old value.

Reproduce:
- Sales/Low Inventory
- Enter 10 for Forty Creek Barrel Select Whisky (currently shows 15)
- Enter 2 for Smirnoff Ice (@ 34)
- Click Submit Inventory
- Click OK on the Success Modal
- Navigate back to the Sales/Low Inventory
- see Forty Creek Barrel Select Whisky (@15)
- see Smirnoff Ice (@34)

Nothing seemed to take effect.

High Priority

@mpatrick8303 
@EliZukowski16 
@lslemp1

**Comment by mpatrick8303** [comment]
ready to verify @thurston-ssa

**Comment by thurston-ssa** [comment]
Verified/closing
